### ISSUE TITLE
Pip install doesn't work :/

### ISSUE THREAD

**Issue by Salz0** [jalan/pdftotext#84] opened 2021-06-06 12:47 UTC
```py
(pdf2textt) C:\Users\korol\PycharmProjects\pdf2text>pip install pdftotext
Collecting pdftotext
  Using cached pdftotext-2.1.6.tar.gz (99 kB)
Building wheels for collected packages: pdftotext
  Building wheel for pdftotext (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\korol\Envs\pdf2textt\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\korol\\AppData\\Local\\Temp\\pip-install-xgd91uva\\pdftotext_8de3931185f44d26a34779ff1902d
1b5\\setup.py'"'"'; __file__='"'"'C:\\Users\\korol\\AppData\\Local\\Temp\\pip-install-xgd91uva\\pdftotext_8de3931185f44d26a34779ff1902d1b5\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file
__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\korol\AppData\Local\Temp\p
ip-wheel-8jdr6dge'
       cwd: C:\Users\korol\AppData\Local\Temp\pip-install-xgd91uva\pdftotext_8de3931185f44d26a34779ff1902d1b5\
  Complete output (71 lines):
  WARNING: pkg-config not found--guessing at poppler version.
           If the build fails, install pkg-config and try again.
  WARNING: pkg-config not found--guessing at poppler version.
           If the build fails, install pkg-config and try again.
  running bdist_wheel
  running build
  running build_ext
  building 'pdftotext' extension
  creating build
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPOPPLER_CPP_AT_LEAST_0_30_0=1 -DPOPPLER_CPP_AT_LEAST_0_58_0=1 -IC:\Users\korol\E
nvs\pdf2textt\include -Ic:\users\korol\appdata\local\programs\python\python39\include -Ic:\users\korol\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.
28.29333\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\i
nclude\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /
EHsc /Tppdftotext.cpp /Fobuild\temp.win-amd64-3.9\Release\pdftotext.obj -Wall
  pdftotext.cpp
  C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_io.h(49): warning C4820: '_finddata32i64_t': '4' bytes padding added after data member '_finddata32i64_t::name'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_io.h(54): warning C4820: '_finddata64i32_t': '4' bytes padding added after data member '_finddata64i32_t::attrib'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_io.h(64): warning C4820: '__finddata64_t': '4' bytes padding added after data member '__finddata64_t::attrib'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_io.h(69): warning C4820: '__finddata64_t': '4' bytes padding added after data member '__finddata64_t::name'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\time.h(36): warning C4820: '_timespec64': '4' bytes padding added after data member '_timespec64::tv_nsec'
  C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\time.h(43): warning C4820: 'timespec': '4' bytes padding added after data member 'timespec::tv_nsec'
  c:\users\korol\appdata\local\programs\python\python39\include\object.h(198): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::slot'
  c:\users\korol\appdata\local\programs\python\python39\include\object.h(206): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::flags'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/object.h(228): warning C4820: '_typeobject': '4' bytes padding added after data member '_typeobject::tp_flags'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/object.h(272): warning C4820: '_typeobject': '4' bytes padding added after data member '_typeobject::tp_version_tag'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/bytesobject.h(15): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::ob_sval'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/bytesobject.h(65): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::small_buffer'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/unicodeobject.h(218): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::state'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/unicodeobject.h(626): warning C4820: '<unnamed-tag>': '2' bytes padding added after data member '<unnamed-tag>::readonly'
  c:\users\korol\appdata\local\programs\python\python39\include\longintrepr.h(88): warning C4820: '_longobject': '4' bytes padding added after data member '_longobject::ob_digit'
  c:\users\korol\appdata\local\programs\python\python39\include\memoryobject.h(45): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::flags'
  c:\users\korol\appdata\local\programs\python\python39\include\memoryobject.h(62): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::flags'
  c:\users\korol\appdata\local\programs\python\python39\include\methodobject.h(40): warning C4820: 'PyMethodDef': '4' bytes padding added after data member 'PyMethodDef::ml_flags'
  c:\users\korol\appdata\local\programs\python\python39\include\moduleobject.h(63): warning C4820: 'PyModuleDef_Slot': '4' bytes padding added after data member 'PyModuleDef_Slot::slot'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/code.h(27): warning C4820: 'PyCodeObject': '4' bytes padding added after data member 'PyCodeObject::co_firstlineno'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/code.h(64): warning C4820: 'PyCodeObject': '3' bytes padding added after data member 'PyCodeObject::co_opcache_size'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(16): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::_type'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(19): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::exitcode'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(209): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::parse_argv'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(364): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::legacy_windows_stdio'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(374): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::pathconfig_warnings'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(381): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::module_search_paths_set'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(401): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::skip_source_first_line'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(424): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::_isolated_interpreter'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/pystate.h(65): warning C4820: '_ts': '2' bytes padding added after data member '_ts::recursion_critical'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/pystate.h(73): warning C4820: '_ts': '4' bytes padding added after data member '_ts::use_tracing'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/pystate.h(96): warning C4820: '_ts': '4' bytes padding added after data member '_ts::gilstate_counter'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/pystate.h(130): warning C4820: '_ts': '4' bytes padding added after data member '_ts::coroutine_origin_tracking_depth'
  c:\users\korol\appdata\local\programs\python\python39\include\genobject.h(33): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::gi_running'
  c:\users\korol\appdata\local\programs\python\python39\include\genobject.h(52): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::cr_running'
  c:\users\korol\appdata\local\programs\python\python39\include\genobject.h(67): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::ag_running'
  c:\users\korol\appdata\local\programs\python\python39\include\genobject.h(80): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::ag_running_async'
  c:\users\korol\appdata\local\programs\python\python39\include\descrobject.h(29): warning C4820: 'wrapperbase': '4' bytes padding added after data member 'wrapperbase::offset'
  c:\users\korol\appdata\local\programs\python\python39\include\descrobject.h(33): warning C4820: 'wrapperbase': '4' bytes padding added after data member 'wrapperbase::flags'
  c:\users\korol\appdata\local\programs\python\python39\include\structseq.h(20): warning C4820: 'PyStructSequence_Desc': '4' bytes padding added after data member 'PyStructSequence_Desc::n_in_sequence'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(19): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(23): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(33): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(40): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(49): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(54): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(66): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
  c:\users\korol\appdata\local\programs\python\python39\include\modsupport.h(100): warning C4820: '_PyArg_Parser': '4' bytes padding added after data member '_PyArg_Parser::max'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/import.h(41): warning C4820: '_frozen': '4' bytes padding added after data member '_frozen::size'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/abstract.h(62): warning C4365: 'return': conversion from 'size_t' to 'Py_ssize_t', signed/unsigned mismatch
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/fileutils.h(54): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_dev'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/fileutils.h(56): warning C4820: '_Py_stat_struct': '2' bytes padding added after data member '_Py_stat_struct::st_mode'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/fileutils.h(60): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_rdev'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/fileutils.h(63): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_atime_nsec'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/fileutils.h(65): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_mtime_nsec'
  c:\users\korol\appdata\local\programs\python\python39\include\cpython/fileutils.h(69): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_reparse_tag'
  pdftotext.cpp(3): fatal error C1083: Cannot open include file: 'poppler/cpp/poppler-document.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for pdftotext
  Running setup.py clean for pdftotext
Failed to build pdftotext
Installing collected packages: pdftotext
    Running setup.py install for pdftotext ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\korol\Envs\pdf2textt\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\korol\\AppData\\Local\\Temp\\pip-install-xgd91uva\\pdftotext_8de3931185f44d26a34779ff190
2d1b5\\setup.py'"'"'; __file__='"'"'C:\\Users\\korol\\AppData\\Local\\Temp\\pip-install-xgd91uva\\pdftotext_8de3931185f44d26a34779ff1902d1b5\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__fi
le__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\korol\AppData\Local\Te
mp\pip-record-23448j34\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\korol\Envs\pdf2textt\include\site\python3.9\pdftotext'
         cwd: C:\Users\korol\AppData\Local\Temp\pip-install-xgd91uva\pdftotext_8de3931185f44d26a34779ff1902d1b5\
    Complete output (71 lines):
    WARNING: pkg-config not found--guessing at poppler version.
             If the build fails, install pkg-config and try again.
    WARNING: pkg-config not found--guessing at poppler version.
             If the build fails, install pkg-config and try again.
    running install
    running build
    running build_ext
    building 'pdftotext' extension
    creating build
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPOPPLER_CPP_AT_LEAST_0_30_0=1 -DPOPPLER_CPP_AT_LEAST_0_58_0=1 -IC:\Users\korol
\Envs\pdf2textt\include -Ic:\users\korol\appdata\local\programs\python\python39\include -Ic:\users\korol\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\1
4.28.29333\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10
\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt
 /EHsc /Tppdftotext.cpp /Fobuild\temp.win-amd64-3.9\Release\pdftotext.obj -Wall
    pdftotext.cpp
    C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_io.h(49): warning C4820: '_finddata32i64_t': '4' bytes padding added after data member '_finddata32i64_t::name'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_io.h(54): warning C4820: '_finddata64i32_t': '4' bytes padding added after data member '_finddata64i32_t::attrib'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_io.h(64): warning C4820: '__finddata64_t': '4' bytes padding added after data member '__finddata64_t::attrib'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\corecrt_io.h(69): warning C4820: '__finddata64_t': '4' bytes padding added after data member '__finddata64_t::name'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\time.h(36): warning C4820: '_timespec64': '4' bytes padding added after data member '_timespec64::tv_nsec'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\time.h(43): warning C4820: 'timespec': '4' bytes padding added after data member 'timespec::tv_nsec'
    c:\users\korol\appdata\local\programs\python\python39\include\object.h(198): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::slot'
    c:\users\korol\appdata\local\programs\python\python39\include\object.h(206): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::flags'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/object.h(228): warning C4820: '_typeobject': '4' bytes padding added after data member '_typeobject::tp_flags'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/object.h(272): warning C4820: '_typeobject': '4' bytes padding added after data member '_typeobject::tp_version_tag'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/bytesobject.h(15): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::ob_sval'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/bytesobject.h(65): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::small_buffer'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/unicodeobject.h(218): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::state'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/unicodeobject.h(626): warning C4820: '<unnamed-tag>': '2' bytes padding added after data member '<unnamed-tag>::readonly'
    c:\users\korol\appdata\local\programs\python\python39\include\longintrepr.h(88): warning C4820: '_longobject': '4' bytes padding added after data member '_longobject::ob_digit'
    c:\users\korol\appdata\local\programs\python\python39\include\memoryobject.h(45): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::flags'
    c:\users\korol\appdata\local\programs\python\python39\include\memoryobject.h(62): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::flags'
    c:\users\korol\appdata\local\programs\python\python39\include\methodobject.h(40): warning C4820: 'PyMethodDef': '4' bytes padding added after data member 'PyMethodDef::ml_flags'
    c:\users\korol\appdata\local\programs\python\python39\include\moduleobject.h(63): warning C4820: 'PyModuleDef_Slot': '4' bytes padding added after data member 'PyModuleDef_Slot::slot'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/code.h(27): warning C4820: 'PyCodeObject': '4' bytes padding added after data member 'PyCodeObject::co_firstlineno'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/code.h(64): warning C4820: 'PyCodeObject': '3' bytes padding added after data member 'PyCodeObject::co_opcache_size'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(16): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::_type'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(19): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::exitcode'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(209): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::parse_argv'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(364): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::legacy_windows_stdio'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(374): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::pathconfig_warnings'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(381): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::module_search_paths_set'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(401): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::skip_source_first_line'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/initconfig.h(424): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::_isolated_interpreter'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/pystate.h(65): warning C4820: '_ts': '2' bytes padding added after data member '_ts::recursion_critical'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/pystate.h(73): warning C4820: '_ts': '4' bytes padding added after data member '_ts::use_tracing'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/pystate.h(96): warning C4820: '_ts': '4' bytes padding added after data member '_ts::gilstate_counter'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/pystate.h(130): warning C4820: '_ts': '4' bytes padding added after data member '_ts::coroutine_origin_tracking_depth'
    c:\users\korol\appdata\local\programs\python\python39\include\genobject.h(33): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::gi_running'
    c:\users\korol\appdata\local\programs\python\python39\include\genobject.h(52): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::cr_running'
    c:\users\korol\appdata\local\programs\python\python39\include\genobject.h(67): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::ag_running'
    c:\users\korol\appdata\local\programs\python\python39\include\genobject.h(80): warning C4820: '<unnamed-tag>': '4' bytes padding added after data member '<unnamed-tag>::ag_running_async'
    c:\users\korol\appdata\local\programs\python\python39\include\descrobject.h(29): warning C4820: 'wrapperbase': '4' bytes padding added after data member 'wrapperbase::offset'
    c:\users\korol\appdata\local\programs\python\python39\include\descrobject.h(33): warning C4820: 'wrapperbase': '4' bytes padding added after data member 'wrapperbase::flags'
    c:\users\korol\appdata\local\programs\python\python39\include\structseq.h(20): warning C4820: 'PyStructSequence_Desc': '4' bytes padding added after data member 'PyStructSequence_Desc::n_in_sequence'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(19): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(23): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(33): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(40): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(49): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(54): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/pyerrors.h(66): warning C4820: '<unnamed-tag>': '7' bytes padding added after data member '<unnamed-tag>::suppress_context'
    c:\users\korol\appdata\local\programs\python\python39\include\modsupport.h(100): warning C4820: '_PyArg_Parser': '4' bytes padding added after data member '_PyArg_Parser::max'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/import.h(41): warning C4820: '_frozen': '4' bytes padding added after data member '_frozen::size'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/abstract.h(62): warning C4365: 'return': conversion from 'size_t' to 'Py_ssize_t', signed/unsigned mismatch
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/fileutils.h(54): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_dev'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/fileutils.h(56): warning C4820: '_Py_stat_struct': '2' bytes padding added after data member '_Py_stat_struct::st_mode'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/fileutils.h(60): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_rdev'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/fileutils.h(63): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_atime_nsec'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/fileutils.h(65): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_mtime_nsec'
    c:\users\korol\appdata\local\programs\python\python39\include\cpython/fileutils.h(69): warning C4820: '_Py_stat_struct': '4' bytes padding added after data member '_Py_stat_struct::st_reparse_tag'
    pdftotext.cpp(3): fatal error C1083: Cannot open include file: 'poppler/cpp/poppler-document.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\korol\Envs\pdf2textt\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\korol\\AppData\\Local\\Temp\\pip-install-xgd91uva\\pdft
otext_8de3931185f44d26a34779ff1902d1b5\\setup.py'"'"'; __file__='"'"'C:\\Users\\korol\\AppData\\Local\\Temp\\pip-install-xgd91uva\\pdftotext_8de3931185f44d26a34779ff1902d1b5\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)
(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record
 'C:\Users\korol\AppData\Local\Temp\pip-record-23448j34\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\korol\Envs\pdf2textt\include\site\python3.9\pdftotext' Check the logs for full com
mand output.
```

**Comment by jalan** [comment] 2021-06-07 15:35
Duplicate of #16

**Closed by jalan** 2021-06-07 15:35 UTC
Labels: duplicate
