### ISSUE TITLE
Importing Pandas messes up raw mode

### ISSUE THREAD

**Issue by adql** [jalan/pdftotext#54] opened 2019-12-26 12:52 UTC
After importing `pandas`, using `raw=True` fails silently with the result being an arbitrarily short string of the beginning of each pdf page. The length of the string is different on each run.

Steps to reproduce:

1. In a new shell import `pdftotext` and run `pdftotext.PDF(<filename>, raw=True)` to test for successful result.
2. Import `pandas`.
3. Run again the same test.

Python `3.8.0`; pdftotext `2.1.2`; pandas `0.25.3`

**Comment by jalan** [comment] 2019-12-27 21:56
Interesting. Can you provide
 - the output of `pip freeze` (or the equivalent from a different tool if you aren't using pip). Since this might be caused by one of the dependencies pandas uses, I'd like to see the full list.
 - a test script that demonstrates the issue
 - the PDF you used, if it's something you can share

Thanks!

**Comment by jalan** [comment] 2020-08-14 14:26
Ignored my request for over six months--closing.

**Closed by jalan** 2020-08-14 14:26 UTC

**Comment by adql** [comment] 2020-08-16 09:50
Sorry, it went of my radar as I gradually moved away from anything related to Pandas.
